/* 
! DO NOT EDIT THIS FILE
This file is for build script.
You should run it before build.
*/
import { writeFileSync, mkdirSync, existsSync } from "fs"
import { resolve, dirname } from "path"
import logger from "@/utils/logger"

const outputPath = resolve("src/constants/env.ts")
const dir = dirname(outputPath)

if (!existsSync(dir)) {
  mkdirSync(dir, { recursive: true })
}

const keys: string[] = [
  "APPLICATION_ID",
  "PUBLIC_KEY",
  "CLIENT_ID",
  "CLIENT_SECRET",
  "TOKEN",
  "LOGLEVEL",
]

const envEntries = keys.map((key) => {
  const value = process.env[key]
  if (value === undefined) {
    logger.warn(
      `⚠️ Environment variable ${key} is not set, it will be output as an empty string.`,
    )
  }
  return `  ${key}: ${JSON.stringify(value ?? "")},`
})

const fileContent = `// ! 🔒 THIS FILE IS GENERATED BY generate-environment.ts DO NOT EDIT
export const ENV = {
${envEntries.join("\n")}
} as const
`

writeFileSync(outputPath, fileContent)
console.log(`✅ Success! your environment for build is in ${outputPath}`)
